server:
  port: 9002
spring:
  application:
    name: ACCOUNTS-SERVICE
  datasource:
    platform: h2
  jpa:
    defer-datasource-initialization : true
  kafka:
    bootstrap-servers: "<your local address>:9092"
    consumer:
      group-id: "myGroup"
eureka:
  client:
    #should register itself with eureka server
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost